Diffuser:
  num_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
Unet:
  time_embed_dim: 100
DiT:
  n_embd: 384
  n_layer: 2
  n_head: 6

Main:
  device: 'cuda'
  batch_size: 16
  num_timesteps: 1000
  epochs: 1
  lr: 1e-3
  model_type: 'dit_beta'
  data: 'ImageNet'
